### PR TITLE
admin: fix select2 by adding bundle

### LINKED ISSUE #2690: Flask-Admin - jquery errors
Hi guys,
I tried to use the admin interface but I received many errors.
E.g. if I go to the Role Admin page ( */admin/accrole/* ), firebug show me these errors:

```
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/vendor/select2/select2-bootstrap3.css"
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/admin/js/filters-1.0.0.js"
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/admin/js/form-1.0.0.js"
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/admin/js/filters-1.0.0.js"
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/admin/js/form-1.0.0.js"
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/admin/js/actions-1.0.0.js"
ReferenceError: AdminModelActions is not defined
ReferenceError: jQuery is not defined
```

Something is gone wrong in my environment or also you have this problem? :)

### LINKED ISSUE #2781: admin: admin/ page dropdown not working with ASSETS_DEBUG=False
When running in production, admin/ pages are currently broken.

With `ASSETS_DEBUG=True` they work but there is an error in the console:

```javascript
 Uncaught ReferenceError: jQuery is not defined select2.min.js:21
```

So probably the assets build is failing for admin/ pages and Bootstrap.js is not available.

### PR DESCRIPTION
**Pull request by jirikuncar**
* FIX Adds `admin.js` bundle that loads `select2.js` library on `/admin`
  pages.  (closes #2690) (closes #2781)

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

### CODE REVIEW

File: invenio/base/static/js/admin.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+ * General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with Invenio; if not, write to the Free Software Foundation, Inc.,
+ * 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
+ */
+
+require([
+    "jquery",
```
Comment (bouzlibop) [inline invenio/base/static/js/admin.js]: I think it should be 2 spaces?

**Comment by bouzlibop** [comment]
working for me too:
* assets build with `ASSETS_DEBUG` `True`/`False` :heavy_check_mark:
* admin view dropdowns :heavy_check_mark:

File: invenio/base/static/js/admin.js (hunk 1 above)
Comment (jirikuncar) [inline invenio/base/static/js/admin.js]: fixed
